### ISSUE TITLE
`tmt run --id ABC finish` ends with traceback

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#222] opened 2020-04-28 15:03 UTC
I'm using #218 and following execution ends with traceback.
1. tmt run --id ABC discover provision
2. tmt run --id ABC finish

There is no traceback if 'finish' is part of a run e.g. ` tmt run  discover provision finish`

Note that it does the 'finish' (no VM is kept running).

```python
/var/tmp/tmt/ABC

/tests/plan-name
    finish
        guest: stopped
        guest: removed
Traceback (most recent call last):
  File "/home/lzachar/.virtualenvs/tmt/bin/tmt", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/lzachar/_important_/Gits/tmt/bin/tmt", line 10, in <module>
    tmt.cli.main()
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.7/site-packages/click/core.py", line 1164, in invoke
    return _process_result(rv)
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.7/site-packages/click/core.py", line 1102, in _process_result
    **ctx.params)
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lzachar/_important_/Gits/tmt/tmt/cli.py", line 268, in finito
    context.obj.run.go()
  File "/home/lzachar/_important_/Gits/tmt/tmt/base.py", line 734, in go
    plan.go()
  File "/home/lzachar/_important_/Gits/tmt/tmt/base.py", line 447, in go
    self.finish.go()
  File "/home/lzachar/_important_/Gits/tmt/tmt/steps/finish/__init__.py", line 35, in go
    guest.remove()
  File "/home/lzachar/_important_/Gits/tmt/tmt/steps/provision/testcloud.py", line 396, in remove
    self.instance.remove(autostop=True)
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.7/site-packages/testcloud/instance.py", line 501, in remove
    shutil.rmtree(self.path)
  File "/home/lzachar/.virtualenvs/tmt/lib64/python3.7/shutil.py", line 485, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/home/lzachar/.virtualenvs/tmt/lib64/python3.7/shutil.py", line 483, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/testcloud/instances/CwlvgWsoLCvRLbbs'
```

**Comment by psss** [comment] 2020-04-28 15:05
I see, this is caused by incomplete `testcloud` wake up. Will look into that.

**Comment by psss** [comment] 2020-04-28 16:12
Should be fixed in 3e8b033. Example output:

```
> tmt run -i 123 plan --name smoke discover provision -h virtual prepare
/var/tmp/tmt/123

/plans/smoke
    discover
        how: shell
        directory: /home/psss/git/tmt
        summary: 1 test selected
    provision
        how: virtual
        image: fedora
        user: root
        memory: 2048 MB
        disk: 10 GB
        progress: booting...
        distro: Fedora release 33 (Rawhide)
        kernel: 5.7.0-0.rc3.1.fc33.x86_64
        summary: 1 guest provisioned
    prepare
        summary: 0 preparations applied

> tmt run -i 123 execute
/var/tmp/tmt/123

/plans/smoke
    execute
        how: shell
        ...
        result: 0 tests passed, 1 test failed

> tmt run -i 123 execute
/var/tmp/tmt/123

/plans/smoke
    execute
        how: shell
        ...
        result: 0 tests passed, 1 test failed

> tmt run -i 123 execute
/var/tmp/tmt/123

/plans/smoke
    execute
        how: shell
        ...
        result: 0 tests passed, 1 test failed

> tmt run -i 123 finish 
/var/tmp/tmt/123

/plans/smoke
    finish
        guest: stopped
        guest: removed
```

**Comment by psss** [comment] 2020-04-28 16:14
And thanks for catching this, Lukáš!

**Comment by lukaszachy** [comment] 2020-04-28 18:54
Thanks for fixing it that fast.

**Closed** 2020-04-29 06:34 UTC
Labels: bug, provision, testcloud
