### ISSUE TITLE
Can't access correct directory when in `prepare` when using `-h shell`

### ISSUE THREAD

**Issue by pvalena** [psss/tmt#497] opened 2020-12-22 01:15 UTC
I think this affects only `virtual` provisioning. The container works fine for me.

I run the test, with prepare -h shell and some script. It relies on the current directory, as I need to access local files from the script (the script itself is unerelevant; I could paste the code instead).

Example, not tested:
```yaml

prepare:
    - name: this does not work in VM
      script: ls ../discover/default/tests/

```

If I access the failed run (I've run it with `--skip finish`), and run the EXACT command that's in `prepare`, it succeeds:

```console
$ tmt run -l login -s prepare:start
[root@testcloud prepare]# ls ../discover/default/tests/
 -> ok
```

Full log: https://git.io/JLBBe
(in log, the first `login` fails with `--when error --when failure`, but that's a separate issue)

**Comment by psss** [comment] 2021-01-04 13:47
Is this possibly a duplicate of #423 where we've discussed that different steps should be executed in the same directory? Could you please review if the proposed `tree` directory would resolve your use case as well? Thanks.

**Comment by pvalena** [comment] 2021-01-05 15:32
> Is this possibly a duplicate of #423 where we've discussed that different steps should be executed in the same directory? Could you please review if the proposed `tree` directory would resolve your use case as well? Thanks.

I don't think this issue is relevant to what I've encountered. I'm fine with __any__ directory.

I should have probably mentioned an error, from the log:
```
bash: line 0: cd: /var/tmp/tmt/run-110/ci-testing/prepare: No such file or directory
```

Please also note:

 - This affects only `virtual` provisioning.
 - This issues does not manifest when I login before the step and run the command manually (even the folder works).
 - I cannot explain the error above.

**Comment by pvalena** [comment] 2021-01-12 18:26
I've just discovered the location that I'm in is `/root`:

```
[ . . . ]
    prepare
        how: install
        name: Install Dependencies
        copr: pvalena/bughunting
        package: bughunting, bughunting-client, bughunting-server and 5 more
        how: shell
        name: Build and install tasks
        overview: 1 script found

stdout (4/4 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root
              total        used        free      shared  buff/cache   available
Mem:          5.8Gi       113Mi       5.0Gi       0.0Ki       695Mi       5.5Gi
Swap:            0B          0B          0B

stderr (19/19 lines)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Warning: Permanently added '192.168.122.131' (ECDSA) to the list of known hosts.
bash: line 0: cd: /var/tmp/tmt/run-003/ci-testing/prepare: No such file or directory
+ pwd
+ free -h
[ . . . ]
```

The relevant part in `ci.fmf` (prepare):
```
    - name: Build and install tasks
      script: |
              set -xe
              pwd
              free -h
              /usr/share/bughunting/scripts/build_tasks.sh ../discover/default/tests/
```

You see, how is it possible the folder does not exist- also failure to "CD" into it should fail `tmt` IMO:
```
bash: line 0: cd: /var/tmp/tmt/run-003/ci-testing/prepare: No such file or directory
```
(is what `tmt` runs)

Ideas?

**Comment by pvalena** [comment] 2021-01-13 04:02
A hack that works around this:
```shell
$ tmt run -av login -s prepare:start
/var/tmp/tmt/run-006
Found 1 plan.
[ . . . ]
    prepare
        login: Starting interactive shell
Warning: Permanently added '192.168.122.51' (ECDSA) to the list of known hosts.
[root@testcloud prepare]# exit
Connection to 192.168.122.51 closed.
        login: Interactive shell finished
        how: install
        name: Install Dependencies
        copr: pvalena/bughunting
        package: 8 packages requested
            bughunting
            bughunting-client
            bughunting-server
            git
            make
            perl-YAML-Syck
            procps-ng
            rpm-build
        how: shell
        name: Build and install tasks
        overview: 1 script found
        script: /usr/share/bughunting/scripts/build_tasks.sh ../discover/default/tests/
        how: shell
[ . . . ]
```
_Note that `        script: /usr/share/bughunting/scripts/build_tasks.sh ../discover/default/tests/` would fail for me if I didn't use the `login`._

**Comment by thrix** [comment] 2021-03-03 09:58
yep we use the same hack. i will try to deliver this after I am done with my current PR

**Comment by jscotka** [comment] 2021-03-09 13:59
Could be fixed by: https://github.com/psss/tmt/pull/623

**Comment by psss** [comment] 2021-03-11 17:43
The issue described here should be covered by solution for #423. Marking as a duplicate.

**Closed by psss** 2021-03-11 17:43 UTC
Labels: prepare
