### ISSUE TITLE
tmt minutet plugin selects wrong rhel version when shot name is used

### ISSUE THREAD

**Issue by RHEmployee** [psss/tmt#557] opened 2021-02-16 13:57 UTC
Hello.

Looks like minute plugin select different instance when called by short name.

8.3 is selected instead of 8.x where x is bigger than 3.

How:
$ tmt run -vvvddd provision -h minute -i rhel-8 login finish

...
1MT-RHEL-8.3.0-released
...

\# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.3 (Ootpa)

VS

$ 1minutetip -n rhel-8
1MT-RHEL-8.x.0-20210216

where x is bigger than 3.

**Comment by psss** [comment] 2021-02-16 15:57
The `minute` plugin searches for the last `rhel-8` image with the `released` tag so this seems to be expected. Would you expect or propose a different behaviour?

**Comment by RHEmployee** [comment] 2021-02-17 09:59
Hi. I'm still confused what minute plugin should do.
I don't know what to propose if I don't know what is should do.
And yes, if this plugin should mimic 1minutetip, then I propose to sync with how 1minutetip behave and how it select instances to work on.

**Comment by stepnem** [comment] 2021-06-11 08:27
I agree the current behaviour breaks the principle of least surprise at least for people used to `1minutetip` (as evidenced by this and other discussions with the users), so if the intention for the plugin is to replace `1minutetip` or provide behaviour consistent with it, it would be better to preserve the `1minutetip` semantics for the interpretation of the image argument.

The `1minutetip` behaviour is IMO also more useful from a common testing workflow perspective, as one is generally mostly testing the latest compose, not the last released version.

**Comment by RHEmployee** [comment] 2021-06-11 08:41
Hello. Just note. Minute plugin in upstream is marked obsolete so this issue should be solved in
downstream.

**Comment by Athwale** [comment] 2021-06-11 08:43
I support the idea of selecting the latest newest image like 1mt does.

**Comment by lukaszachy** [comment] 2021-06-11 09:10
I created downstream issue.

**Comment by FrNecas** [comment] 2021-09-14 11:39
Closing since the issue is already tracked downstream

**Closed by FrNecas** 2021-09-14 11:39 UTC
Labels: minute
