### ISSUE TITLE
tmt plan lint traceback if description contains "tier: 1"

### ISSUE THREAD

**Issue by Athwale** [psss/tmt#114] opened 2020-02-18 10:05 UTC
Hi,

When you run tmt plan lint on a file with description like this:
description:
    This special plan selects "tier: 1" tests to be run.
    Next line of description...

You will get a traceback. The problem is the tier: 1
fmf.utils.FileError: Failed to parse 'plans/ci.fmf'
mapping values are not allowed here

Removing the ' : ' from the file fixes the problem. 
I think the description part of the file should allow anything to be written there.

**Comment by psss** [comment] 2020-02-27 14:00
The traceback should be fixed 653a877. However the problem you describe above is caused by invalid yaml syntax which is used by `fmf` for parsing metadata. If you need colons in a longer text you can use blocks:

    description-wrap: >
        This special plan selects "tier: 1" tests to be run.
        Next line of description will be paragraph-wrapped.
    description-keep: |
        This special plan selects "tier: 1" tests to be run.
        Next line of description will be kept.

Does that help?

**Comment by Athwale** [comment] 2020-02-28 10:15
Yes, thank you.

**Closed** 2020-03-02 08:10 UTC
Labels: bug
