### ISSUE TITLE
prepare:script tries to `cd` into nonexistent directory

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#587] opened 2021-02-25 09:45 UTC
I have prepare step with 'script' option. In the log.txt I see 
```
prepare
        workdir: /var/tmp/tmt/run-206/prepare
        Using the 'PrepareInstall' plugin for the 'install' method.
        how: shell
        order: 50
        overview: 1 script found
        script: python3 repro.py
            Execute command 'python3 repro.py' on guest '10.0.137.233'.
            Run command 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@IP cd '/var/tmp/tmt/run-206/prepare'; python3 repro.py'.
        err: bash: line 0: cd: /var/tmp/tmt/run-206/prepare: No such file or directory
```

**Comment by jscotka** [comment] 2021-02-25 12:19
I've found same issue: 
plan file contains:
```
prepare:
  - name: Install Chromium
    script: ./prepare-chromium.sh
```
1. issue is that it is not documented on https://tmt.readthedocs.io/en/latest/spec/steps.html#spec-steps-prepare-shell what will be the current dir for the execution so not easy to find, how to execute my own prepare scripts
2. second is right your issue:
```
Warning: Permanently added '192.168.122.231' (ECDSA) to the list of known hosts.
bash: line 0: cd: /var/tmp/tmt/run-012/plans/upstream/prepare: No such file or directory
bash: ./prepare-chromium.sh: No such file or directory

Failed to run command 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /var/tmp/tmt/run-012/plans/upstream/provision/default/id_rsa root@192.168.122.231 export TEST_DIR=verify; cd '/var/tmp/tmt/run-012/plans/upstream/prepare'; ./prepare-chromium.sh'.

```

**Comment by jscotka** [comment] 2021-03-02 13:07
@psss @lukaszachy please consider adding it to milestone 1.4

**Comment by lukaszachy** [comment] 2021-03-05 10:20
Yes, we really have to  fix this. - you end up in user home (usually root) but have no idea where to cd to as /var/tmp/... can contain several runs if you are reusing machine (via provision -h connect)

**Comment by pvalena** [comment] 2021-03-05 10:21
I think this is a duplicate of #497 :) but feel free to close that one.

**Comment by jscotka** [comment] 2021-03-05 14:08
> Yes, we really have to fix this. - you end up in user home (usually root) but have no idea where to cd to as /var/tmp/... can contain several runs if you are reusing machine (via provision -h connect)

It is question, but probably or curious it works well with ansible preparating, where documentation says, that you can use local playbook, so what is the location, and where to store these ansible or shell scripts have to be well documented: e.g. it make sense to use current directory where plan is stored, or it also makes sense to be inside git root dir.

Theoretically there will be problem in case in preparation step there is copy of source git code and for execution it will create another copy of git dir what will leads that you cannot affect e.g. current execution process, e.g. add some hacks via preparation. But not sure how it works right now.

@pvalena yes, seems like duplicate.

**Comment by psss** [comment] 2021-03-11 17:44
The issue described here should be covered by solution for #423. Marking as a duplicate.

**Closed by psss** 2021-03-11 17:44 UTC
Labels: bug, must, prepare
